version: "3.9"

services:
  api01: &api
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    image: joaodematejr/imagem-rinha-1-2024:latest
    hostname: api01
    container_name: api01
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    environment:
      - MONGO_URL=mongodb://admin:admin@db:27017
    # Não é necessário expor qualquer porta além da porta do load balancer,
    # mas é comum as pessoas o fazerem para testarem suas APIs e conectarem
    # ao banco de dados na fase de desenvolvimento.
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "300MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    container_name: api02
    environment:
      - MUX_HOST=api02
      - MONGO_URL=mongodb://admin:admin@db:27017
    ports:
      - "8082:8080"
  nginx:
   image: nginx:1.25.3-alpine
   container_name: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
     - api01
     - api02
   ports:
    - "9999:9999"
   deploy:
     resources:
       limits:
        cpus: "0.15"
        memory: "10MB"

  db:
    image: mongo:latest
    restart: always
    hostname: db
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=rinha
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_PORT=27017
      - MONGO_INITDB_ENABLE_MAJORITY_READ_CONCERN=1  
      - MONGO_INITDB_ENABLE_MAJORITY_WRITE_CONCERN=1
      - MONGO_INITDB_WIREDTIGER_CACHE_SIZE_MB=400
      - MONGO_MAX_CONNECTIONS=200
    ports:
      - "27017:27017"
    command: mongod --setParameter=maxIndexBuildMemoryUsageMegabytes=140
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "240MB"

networks:
  rinha-nginx-2024q1:
    name: rinha-nginx-2024q1
    driver: bridge
