version: "3.9"

services:
  api01: &api
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    image: joaodematejr/imagem-rinha-1-2024:latest
    hostname: api01
    container_name: api01
    environment:
      - MONGO_URL=mongodb://admin:admin@db:27017
    # Não é necessário expor qualquer porta além da porta do load balancer,
    # mas é comum as pessoas o fazerem para testarem suas APIs e conectarem
    # ao banco de dados na fase de desenvolvimento.
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      #resources:
        #limits:
          #cpus: "0.15"
          #memory: "15MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    container_name: api02
    environment:
      - MUX_HOST=api02
      - MONGO_URL=mongodb://admin:admin@db:27017/rinha?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=10&minPoolSize=5&waitQueueMultiple=10&waitQueueTimeoutMS=360000&readPreference=primary&writeConcern=majority&readConcern=majority      
    ports:
      - "8082:8080"
    deploy:


  nginx:
   image: nginx:1.25.3-alpine
   container_name: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
     - api01
     - api02
   ports:
    - "9999:9999"
   deploy:
     #resources:
       #limits:
        #cpus: '0.25'
        #memory: "35MB"

  db:
    image: mongo:7-jammy
    restart: always
    hostname: db
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=rinha
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_PORT=27017
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      #resources:
        #limits:
          #cpus: '0.75'
          #memory: '425MB'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh db:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  rinha-nginx-2024q1:
    name: rinha-nginx-2024q1
    driver: bridge
