version: "3.7"

services:
  db:
    image: mongo:latest
    container_name: rinha_container_mongo
    environment:
      - MONGO_INITDB_DATABASE=rinha
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
    - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rinha_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "330MB"
networks:
  rinha_network:
    name: rinha_network
    driver: bridge